### ISSUE TITLE
Need to add DrugZ to this list

### ISSUE THREAD

**Issue by cetienn01** [davidliwei/awesome-CRISPR#14]
The Hart lab (creators of BAGEL and PICKLES software) also recently published DrugZ, a new algorithm to perform data analysis on CRISPR screens.
--See the links below for more details.
(1) GitHub page
https://github.com/hart-lab/drugz
(2) Published article
https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-019-0665-3
-CE

**Comment by davidliwei** [comment]
Updated DrugZ into the list

**Comment by cetienn01** [comment]
Awesome!
